version: '3.3'

services:
    # Database
  db:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=ls-ca55893ba6d2224690c5161971f88beb5c1f3af7.ctwkii6wuxm1.ap-northeast-2.rds.amazonaws.com
      - MYSQL_USER=dbmasteruser
      - MYSQL_ROOT_PASSWORD=RooTUsEr!1020
      - MYSQL_DATABASE=new_g-exam

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./g-exam-front/build:/usr/share/nginx/html

  server:
    build:
      context: ./g-exam-back/
    container_name: server
    restart: "on-failure"
    expose:
      - 4000
    volumes:
      - './g-exam-back:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true