version: '3'

services:
  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend
    depends_on:
      - web
      - app

  # Frontend
  web:
    build: 
      context: ./g-exam-front
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ./g-exam-front:/app
      - node_modules:/g-exam-front/node_modules
    networks:
      - frontend
    depends_on:
      - app

  # Backend
  app:
    build:
      context: ./g-exam-back
      dockerfile: Dockerfile
    expose:
      - "4000"
    volumes:
      - ./g-exam-back:/server
      - node_modules:/g-exam-back/node_modules
    networks:
      - backend
      - frontend
    depends_on:
      - db

  # Database
  db:
    image: "mysql:8.1"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=My19971108!
      - MYSQL_DATABASE=new_g-exam
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:
  node_modules:

networks:
  frontend:
  backend:
