version: '3.8'

services:
  frontend:
    restart: always
    build:
      context: ./g-exam-front
      dockerfile: Dockerfile
    ports:
      - "80:80"  # 프론트엔드 서비스가 사용할 포트
    # 필요한 설정 추가 가능

  backend:
    restart: always
    build:
      context: ./g-exam-back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # 백엔드 서비스가 사용할 포트
    # 필요한 설정 추가 가능
